name: transformer_page_view
description: PageTransformer for flutter
version: 0.1.6
author: JZoom <jzoom8112@gmail.com>
homepage:  https://github.com/jzoom/transformer_page_view

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
